server:
  port: 4004

spring:
  cloud:
    gateway:
      routes:
        # REST client -> http://localhost:4004/api/patients
        # API Gateway -> http://patient-service:4000/patients
        - id: patient-service-route
          uri: http://patient-service:4000
          predicates:
            - Path=/api/patients/**
          filters:
            - StripPrefix=1

        - id: auth-service-route
          uri: http://auth-service:4005
          predicates:
            - Path=/auth/**
          filters:
            - StripPrefix=1
